"""new migrations

Revision ID: 754f84eb24eb
Revises: 2dc41a65fff6
Create Date: 2026-03-23 21:18:19.287959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '754f84eb24eb'
down_revision: Union[str, Sequence[str], None] = '2dc41a65fff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'reservations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_column('reservations', 'user_id')
    # ### end Alembic commands ###
